using TripPin.Application.Abstractions;
using TripPin.Application.People.Models;
using TripPin.Application.People.Ports;
using TripPin.Domain.Common;
using TripPin.Domain.People;

namespace TripPin.Application.Tests.Fakes;

/// <summary>
/// Hand-written stand-in for <see cref="IPeopleRepository"/>.
/// </summary>
/// <remarks>
/// Written out rather than generated by a mocking library because these tests
/// assert on what the handler passed down, which a recording fake states more
/// plainly than a chain of argument matchers.
/// </remarks>
internal sealed class FakePeopleRepository : IPeopleRepository
{
    private static readonly PagedResult<PersonSummary> EmptyPage = new([], 0, 1, 8);

    public int ListCalls { get; private set; }

    public int SearchCalls { get; private set; }

    public int GetByIdCalls { get; private set; }

    public int GetForUpdateCalls { get; private set; }

    public int UpdateCalls { get; private set; }

    public PersonUpdate? LastUpdate { get; private set; }

    public PersonFilter? LastFilter { get; private set; }

    public UserName? LastUserName { get; private set; }

    public int? LastPage { get; private set; }

    public int? LastPageSize { get; private set; }

    public CancellationToken LastCancellationToken { get; private set; }

    public Result<ConcurrencyToken> UpdateResult { get; set; } =
        Result<ConcurrencyToken>.Success(ConcurrencyToken.From("W/\"updated\""));

    public Result<Person>? GetByIdResult { get; set; }

    public Result<PagedResult<PersonSummary>> ListResult { get; set; } =
        Result<PagedResult<PersonSummary>>.Success(EmptyPage);

    public Task<Result<PagedResult<PersonSummary>>> ListAsync(
        int page,
        int pageSize,
        CancellationToken cancellationToken)
    {
        ListCalls++;
        LastPage = page;
        LastPageSize = pageSize;
        LastCancellationToken = cancellationToken;

        return Task.FromResult(ListResult);
    }

    public Task<Result<PagedResult<PersonSummary>>> SearchAsync(
        PersonFilter filter,
        int page,
        int pageSize,
        CancellationToken cancellationToken)
    {
        SearchCalls++;
        LastFilter = filter;
        LastPage = page;
        LastPageSize = pageSize;
        LastCancellationToken = cancellationToken;

        return Task.FromResult(ListResult);
    }

    public Task<Result<Person>> GetByIdAsync(
        UserName userName,
        CancellationToken cancellationToken)
    {
        GetByIdCalls++;
        LastUserName = userName;
        LastCancellationToken = cancellationToken;

        return Task.FromResult(
            GetByIdResult ?? Result<Person>.NotFound("Person not found."));
    }

    public Task<Result<Person>> GetForUpdateAsync(
        UserName userName,
        CancellationToken cancellationToken)
    {
        GetForUpdateCalls++;
        LastUserName = userName;
        LastCancellationToken = cancellationToken;

        return Task.FromResult(
            GetByIdResult ?? Result<Person>.NotFound("Person not found."));
    }

    public Task<Result<ConcurrencyToken>> UpdateAsync(
        PersonUpdate update,
        CancellationToken cancellationToken)
    {
        UpdateCalls++;
        LastUpdate = update;
        LastCancellationToken = cancellationToken;

        return Task.FromResult(UpdateResult);
    }
}
